services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file: '.env'
    healthcheck:
      test: ['CMD', 'pg_isready -U admin -d test']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
